### ISSUE TITLE
Can it generate LICENSE?

### ISSUE THREAD

**Issue by Freed-Wu** [iamcco/coc-gitignore#2]
it is amazing that this plugin can generate gitignore automatically! can it generate LICENSE(e.g. GPLv3, MIT?) it looks similar to it.
thanks!

**Comment by iamcco** [comment]
It can't.

**Comment by Freed-Wu** [comment]
No serious. I have created a [coc extension](https://github.com/Freed-Wu/coc-license) to do this work.
